image: smallerinfinity/monomyth-ci

stages:
  - test

test:
  stage: test
  services:
    - rabbitmq:latest
  variables:
    TEST_RMQ: "rabbitmq"
    TEST_RMQ_DEFAULT_USER: "guest"
    TEST_RMQ_DEFAULT_PASS: "guest"
  before_script:
    - qlot install
    - ln -s /builds/smaller_infinity/monomyth /root/.roswell/local-projects/monomyth
  script:
    - qlot exec ./bin/test.ros
  only:
    - merge_request
    - develop
    - master
