version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${TEST_RMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${TEST_RMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
