version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${TEST_RMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${TEST_RMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: monomyth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
